spring:
  application:
    name: teacher-service


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/tandem




  datasource:
    url: jdbc:postgresql://localhost:5462/teacherDB
    username: postgresteacher
    password: postgresteacher
    driver-class-name: org.postgresql.Driver



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 10001